[package]
name = "rayimg"
authors = ["ivan0sokin"]
version = "0.0.4"
edition = "2021"
description = "Renders image of some scene using ray tracing."
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/rayimg"
repository = "https://github.com/ivan0sokin/rayimg"

[dependencies]
rand = "0.8.5"