[package]
name = "rayimg"
authors = ["ivan0sokin"]
version = "0.0.2"
edition = "2021"
description = "Renders image of some scene using ray tracing."
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rayimg"
repository = "https://github.com/ivan0sokin/rayimg"

[dependencies]